config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  get '/index'        => 'pages#index',         as: :home
  get '/onboarding'   => 'pages#onboarding',    as: :onboarding
  get '/about'        => 'pages#about',         as: :about
  get '/contact'      => 'pages#contact',       as: :contact
  get '/faq'          => 'pages#faq',           as: :faq
  get '/terms'        => 'pages#terms',         as: :terms
  get '/privacy'      => 'pages#privacy',       as: :privacy
  get '/login'        => 'pages#login',         as: :login
  get '/signup'       => 'pages#signup',        as: :signup

  get '/overview'         => 'overview#title',    as: :overview_title
  get '/overview/intro'   => 'overview#intro',    as: :overview_intro
  get '/overview/recap'   => 'overview#recap',    as: :overview_recap
  get '/overview/s0_1'    => 'overview#s0_1',     as: :s0_1
  get '/overview/s0_2'    => 'overview#s0_2',     as: :s0_2
  get '/overview/s0_3'    => 'overview#s0_3',     as: :s0_3

  get 'section/1/title'   => 'step1#title',   as: :title_1
  get 'section/1/intro'   => 'step1#intro',   as: :intro_1
  get 'section/1/recap'   => 'step1#recap',   as: :recap_1
  get 'section/1/s1_1'    => 'step1#s1_1',    as: :s1_1
  get 'section/1/s1_2'    => 'step1#s1_2',    as: :s1_2
  get 'section/1/s1_3'    => 'step1#s1_3',    as: :s1_3

  get 'section/2/title'   => 'step2#title',   as: :title_2
  get 'section/2/intro'   => 'step2#intro',   as: :intro_2
  get 'section/2/recap'   => 'step2#recap',   as: :recap_2
  get 'section/2/s2_1'    => 'step2#s2_1',    as: :s2_1
  get 'section/2/s2_2'    => 'step2#s2_2',    as: :s2_2
  get 'section/2/s2_3'    => 'step2#s2_3',    as: :s2_3
  get 'section/2/s2_4'    => 'step2#s2_4',    as: :s2_4
  get 'section/2/s2_5'    => 'step2#s2_5',    as: :s2_5

  get 'section/3/title'   => 'step3#title',   as: :title_3
  get 'section/3/intro'   => 'step3#intro',   as: :intro_3
  get 'section/3/recap'   => 'step3#recap',   as: :recap_3
  get 'section/3/s3_1'    => 'step3#s3_1',    as: :s3_1
  get 'section/3/s3_2'    => 'step3#s3_2',    as: :s3_2
  get 'section/3/s3_3'    => 'step3#s3_3',    as: :s3_3

  get 'section/4/title'   => 'step4#title',   as: :title_4
  get 'section/4/intro'   => 'step4#intro',   as: :intro_4
  get 'section/4/recap'   => 'step4#recap',   as: :recap_4
  get 'section/4/s4_1'    => 'step4#s4_1',    as: :s4_1
  get 'section/4/s4_2'    => 'step4#s4_2',    as: :s4_2

  get 'section/5/title'   => 'step5#title',   as: :title_5
  get 'section/5/intro'   => 'step5#intro',   as: :intro_5
  get 'section/5/recap'   => 'step5#recap',   as: :recap_5
  get 'section/5/s5_1'    => 'step5#s5_1',    as: :s5_1
  get 'section/5/s5_2'    => 'step5#s5_2',    as: :s5_2
  get 'section/5/s5_3'    => 'step5#s5_3',    as: :s5_3
  get 'section/5/s5_4'    => 'step5#s5_4',    as: :s5_4
  get 'section/5/s5_5'    => 'step5#s5_5',    as: :s5_5

  get 'section/6/title'   => 'step6#title',   as: :title_6
  get 'section/6/intro'   => 'step6#intro',   as: :intro_6
  get 'section/6/recap'   => 'step6#recap',   as: :recap_6
  get 'section/6/s6_0'    => 'step6#s6_0',    as: :s6_0
  get 'section/6/s6_1'    => 'step6#s6_1',    as: :s6_1
  get 'section/6/s6_2'    => 'step6#s6_2',    as: :s6_2
  get 'section/6/s6_3'    => 'step6#s6_3',    as: :s6_3
  get 'section/6/s6_4'    => 'step6#s6_4',    as: :s6_4
  get 'section/6/s6_5'    => 'step6#s6_5',    as: :s6_5

  get "pages/download_pdf"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def onboarding
  end

  def about
  end

  def contact
  end

  def faq
  end

  def terms
  end

  def privacy
  end

  def signup
  end

  def login
  end

  def overview
  end

  def download_pdf
  send_file(
    "#{Rails.root}/public/CUE_Syllabi Review Guide Appendix.pdf",
    filename: "CUE_Syllabi Review Guide Appendix.pdf",
    type: "application/pdf"
  )
end

end

app/controllers/step1_controller.rb
class Step1Controller < ApplicationController
  layout "step1"

  def title
  end

  def intro
  end

  def s1_1
  end

  def s1_2
  end

end

app/controllers/step2_controller.rb
class Step2Controller < ApplicationController
  layout "step2"

  def title
  end

  def intro
  end

  def s2_1
  end

  def s2_2
  end

  def s2_3
  end

  def s2_4
  end

  def s2_5
  end

  def s2_6
  end
end

app/controllers/step3_controller.rb
class Step3Controller < ApplicationController

  def title
  end

  def intro
  end

  def s3_1
  end

  def s3_2
  end

  def s3_3
  end

end

app/controllers/step4_controller.rb
class Step4Controller < ApplicationController
  layout "step4"

  def title
  end

  def intro
  end

  def s4_1
  end

  def s4_2
  end

end

app/controllers/step5_controller.rb
class Step5Controller < ApplicationController
  layout "step5"

  def title
  end

  def intro
  end

  def s5_1
  end

  def s5_2
  end

  def s5_3
  end

  def s5_4
  end

  def s5_5
  end

end

app/controllers/step6_controller.rb
class Step6Controller < ApplicationController
  layout "step6"

  def title
  end

  def intro
  end

  def recap_6
  end

  def s6_0
  end

  def s6_1
  end

  def s6_2
  end

  def s6_3
  end

  def s6_4
  end

end

app/controllers/step_1_controller.rb
class Step1Controller < ApplicationController
  def home
  end

  def grounding_1
  end

  def grounding_2
  end

  def grounding_3
  end

  def grounding_4
  end
end

app/controllers/step_2_controller.rb
class Step2Controller < ApplicationController
  def home
  end

  def context_1
  end

  def context_2
  end

  def context_3
  end

  def context_4
  end
end

app/controllers/step_3_controller.rb
class Step3Controller < ApplicationController
  def home
  end

  def scope_1
  end

  def scope_2
  end

  def scope_3
  end

  def scope_4
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/overview_helper.rb
module OverviewHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/step_1_helper.rb
module Step1Helper
end

app/helpers/step_2_helper.rb
module Step2Helper
end

app/helpers/step_3_helper.rb
module Step3Helper
end

app/helpers/step_4_helper.rb
module Step4Helper
end

app/helpers/step_5_helper.rb
module Step5Helper
end

app/helpers/step_6_helper.rb
module Step6Helper
end

app/views/shared/_bottom_panel.html.erb
<!-- Panel Bottom #02 -->
<nav class="panel bottom forceMobileView">
  <div class="sections desktop">
    <div class="left"></div>
    <div class="center">
			<ul class="menu grid box-87 equal equalMobile">
        <li class="">
         	<a hre="#">
				 		<h3>Step one</h3>
       			<p class="tiny opacity-6">How do you feel?</p>
					</a>
        </li>
        <li class="">
					<a hre="#">
 					 <h3>Step Two</h3>
 					 <p class="tiny opacity-6">Why Syllabi?</p>
 				 </a>
        </li>
        <li class="">
					<a hre="#">
 					 <h3>Step Three</h3>
 					 <p class="tiny opacity-6">What is EQMD?</p>
 				 </a>
        </li>
        <li class="">
         <a hre="#">
					 <h3>Step Four</h3>
					 <p class="tiny opacity-6">EQMD Concepts</p>
				 </a>
        </li>
				<li class="">
				 <a hre="#">
					 <h3>Step Five</h3>
					 <p class="tiny opacity-6">Who Syllabi Serve?</p>
				 </a>
				</li>
				<li class="">
				 <a hre="#">
					 <h3>Step Six</h3>
					 <p class="tiny opacity-6">Analysis</p>
				 </a>
				</li>
      </ul>
    </div>
    <div class="right"><span data-dropdown-id="2" class="button actionButton dropdownTrigger"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#share"></use></svg></span></div>
  </div>
  <div class="sections compact hidden">
    <div class="right"><span data-dropdown-id="2" class="button actionButton dropdownTrigger"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#share"></use></svg></span></div>
  </div>
</nav>

<!-- Share Window -->
<div class="dropdown share bottom right" data-dropdown-id="2" data-text="Take a look at this" data-url="https://designmodo.com" data-pinterest-image="https://designmodo.com/wp-content/uploads/2015/10/Presentation.jpg">
  <div class="center padding-2">
    <div class="title">Share</div>
    <a href="#">Contact us</a>
  </div>
  <ul>
    <li class="social-facebook"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#fb-like"></use></svg></li>
    <li class="social-twitter"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#twitter"></use></svg></li>
    <li class="social-googlePlus"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#googlePlus"></use></svg></li>
    <li class="social-linkedin"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#linkedin"></use></svg></li>
    <li class="mail" data-subject="Subject" data-body="Body">share by email</li>
  </ul>
</div>



<!-- Navigation -->
<nav class="side ">
  <div class="navigation">
    <ul></ul>
  </div>
</nav>

app/views/shared/_css.html.erb
<%= render "shared/fonts" %>
<link rel="stylesheet" as="font" href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,600,700|Material+Icons"/>
<script src="https://kit.fontawesome.com/52be0f6b73.js"></script>
<style>
  .status-on, .fullscreen-on .status-off { display: none; }
  .fullscreen-on .status-on { display: inline-block; }

  typed-cursor{
    opacity: 1;
    -webkit-animation: blink 0.7s infinite;
    animation: blink 0.7s infinite;
  }
  @-webkit-keyframes blink {50%{opacity:0;}}
  @keyframes blink {50%{opacity:0;}}

</style>


<!-- EXAMPLE: Panel Dropdown -->
<!-- 1) Copy styles -->
<style>
  .panel .menu { cursor:pointer;}
  .panel .menu > li {
    outline: none;
    border-radius: 50px;
    padding: 7px 17px;
    will-change: background;
    -webkit-transition:0.25s background;
    transition:0.25s background;
  }
  .panel .menu > li:focus,
  .panel .menu > li:hover {
    background: rgba(0, 0, 0, 0.15);
  }
  .panel .menu > li .material-icons {
    vertical-align: bottom;
    position: relative;
    top: 2px;
    margin-top: -4px;
  }

  .dropdown.customDropdown { padding:10px 0; width: 200px;}
  .dropdown.customDropdown .menu > li:not(.link),
  .dropdown.customDropdown .menu > li.link a { font-size: 15px; padding: 8px 10px 8px 20px; cursor: pointer; display: block; text-align: left; }
  .dropdown.customDropdown .menu > li:hover { background:rgba(0, 0, 0, 0.05);}
  .dropdown.customDropdown .material-icons {
    position: relative;
    top: -3px;
    float: right;
  }
</style>

app/views/shared/_fonts.html.erb
<link rel="stylesheet" as="font" href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,600,700|Material+Icons"/>
<link href="https://fonts.googleapis.com/css?family=Nunito|Nunito+Sans:200,300i,400,600,700,800,900&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Cabin:400,500,600,700|Comfortaa:300,400,500,600,700|Crete+Round|Fredoka+One|Istok+Web:400,700|Lato:300,400,700,900|Libre+Baskerville:400,700|Merriweather:300,400,700,900|Nunito+Sans:200,300i,400,600,700,800,900|Nunito:400,700,800,900|Prata|Righteous|Roboto:400,500,700,900|Rubik:400,500,700,900|Sanchez|Sawarabi+Mincho|Unica+One|Varela+Round|Volkhov&display=swap" rel="stylesheet">
<link href='https://fonts.googleapis.com/css?family=Quicksand:300,400,700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.2/css/all.css" integrity="sha384-XxNLWSzCxOe/CFcHcAiJAZ7LarLmw3f4975gOO6QkxvULbGGNDoSOTzItGUG++Q+" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,700|Roboto+Mono:300,400,500,700|Roboto+Slab:100,300,400,700|Roboto:300,400,500,700,900&display=swap" rel="stylesheet">

<style>
  .quicksand { font-family: 'Quicksand', sans-serif !important; }
</style>

app/views/shared/_js.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<script src="https://cdn.rawgit.com/mattboldt/typed.js/548c6ade/dist/typed.min.js"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js" charset="utf-8"></script>
<!-- Fullscreen Toggle -->
<!-- 1) add plugin -->
<script src="https://cdn.rawgit.com/kayahr/jquery-fullscreen-plugin/9438016e/jquery.fullscreen-min.js"></script>

<!-- 2) add script -->
<script>
  $(function(){
    //HANDLE FULLSCREEN
    $('.fullscreenToggle').click(function(){
      $("body").toggleFullScreen();
    });

    //CONTROL WITH JAVSCRIPT (OPTIONAL)
    $(document).bind("fullscreenchange", function() {
      //control with css, example below
      $html.removeClassByPrefix('fullscreen-').addClass('fullscreen-' + ($(document).fullScreen() ? "on" : "off"));

      //control with JS
      if ($(document).fullScreen()) {
        //your function
      }
    });

    //GO FULLSCREEN ON [F] KEY (OPTIONAL)
    $(document).keyup(function (e) {
      if (e.target.nodeName.toLowerCase() == 'input' || e.target.nodeName.toLowerCase() == 'textarea') {
        return;
      }
      if (e.keyCode == 70) {
        $("body").toggleFullScreen();
      }
    });
  });
</script>

app/views/shared/_navigation.html.erb
<%= render "shared/panel_top" %>
<%= render "shared/sidebar" %>
<%= render "shared/panel_bottom" %>

app/views/shared/_panel_bottom.html.erb
<!-- Panel Bottom #02 -->
<nav class="panel bottom forceMobileView" style="box-shadow: 1px 1px 2px #ccc;">
  <div class="sections desktop">
    <div class="center">
			<ul class="menu text-uppercase width-100p padding-bottom-2">
        <li class="col-2-12">
         	<%= link_to overview_title_path do %>
				 		<h3>Intro</h3>
       			<span class="tiny">Introduction</span>
					<% end %>
        </li>
        <li class="col-2-12">
         	<%= link_to title_1_path do %>
				 		<h3>step One</h3>
       			<span class="tiny">How Do you Feel</span>
					<% end %>
        </li>
        <li class="col-2-12">
					<%= link_to title_2_path do %>
 					 <h3>step Two</h3>
 					 <span class="tiny">Why Syllabi?</span>
 				 <% end %>
        </li>
        <li class="col-2-12">
					<%= link_to title_3_path do %>
 					 <h3>step Three</h3>
 					 <span class="tiny">What is EQMD?</span>
 				 <% end %>
        </li>
        <li class="col-2-12">
         <%= link_to title_4_path do %>
					 <h3>step Four</h3>
					 <span class="tiny">EQMD Concepts</span>
				 <% end %>
        </li>
				<li class="col-2-12">
				 <%= link_to title_5_path do %>
					 <h3>step Five</h3>
					 <span class="tiny">Who Syllabi Serve?</span>
				 <% end %>
				</li>
				<li class="col-2-12">
				 <%= link_to title_6_path do %>
					 <h3>step Six</h3>
					 <span class="tiny">Analysis</span>
				 <% end %>
				</li>
      </ul>
    </div>
  </div>
  <div class="sections compact hidden">
    <div class="right"><span data-dropdown-id="2" class="button actionButton dropdownTrigger"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#share"></use></svg></span></div>
  </div>
</nav>

<!-- Share Window -->
<div class="dropdown share bottom right" data-dropdown-id="2" data-text="Take a look at this" data-url="https://designmodo.com" data-pinterest-image="https://designmodo.com/wp-content/uploads/2015/10/Presentation.jpg">
  <div class="center padding-2">
    <div class="title">Share</div>
    <a href="#">Contact us</a>
  </div>
  <ul>
    <li class="social-facebook"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#fb-like"></use></svg></li>
    <li class="social-twitter"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#twitter"></use></svg></li>
    <li class="social-googlePlus"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#googlePlus"></use></svg></li>
    <li class="social-linkedin"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#linkedin"></use></svg></li>
    <li class="mail" data-subject="Subject" data-body="Body">share by email</li>
  </ul>
</div>




  <!-- <nav class="side ">
    <div class="navigation">
      <ul></ul>
    </div>
  </nav> -->

app/views/shared/_panel_top.html.erb
  <!-- compact version -->
  <div class="sections compact hidden">
    <div class="left"><a href="#" title="Slides Framework"><svg style="width:82px;height:24px"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#logo"></use></svg></a></div>
    <div class="right">
      <!-- <span class="button actionButton sidebarTrigger" data-sidebar-id="1"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#menu"></use></svg></span> -->
      <span class="button actionButton fullscreenToggle white"><i class="material-icons">fullscreen</i></span>
    </div>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<!-- Sidebar -->
<nav class="sidebar" data-sidebar-id="1">
  <div class="close"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#close"></use></svg></div>
  <div class="content">
    <a href="#" class="logo"><svg width="37" height="30"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#logo-icon"></use></svg></a>

    <ul class="mainMenu margin-top-3">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Overview", overview_intro_path %></li>
      <li><%= link_to "Section 1", intro_1_path %></li>
      <li><%= link_to "Section 2", intro_2_path %></li>
      <li><%= link_to "Section 3", intro_3_path %></li>
      <li><%= link_to "Section 4", s5_1_path %></li>
      <li><%= link_to "Section 5", intro_6_path %></li>
    </ul>

    <ul class="mainMenu margin-top-3">
      <li><a href="#">About</a></li>
      <li><a href="#">The Team</a></li>
      <li><a href="#">Downloads</a></li>
      <li><a href="#">CUE Toolkit</a></li>
    </ul>
    <ul class="subMenu small opacity-8">
      <li><a href="#">Help & FAQ</a></li>
			<li><a href="#">Submit Feedback</a></li>
      <li><a href="#">Terms & Conditions</a></li>
      <li><a href="#">Privacy Policy</a></li>
      <li><a href="#">Contact Us</a></li>
    </ul>
    <ul class="social opacity-8">
      <li><a href="#"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#facebook"></use></svg></a></li>
      <li><a href="#"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#twitter"></use></svg></a></li>
    </ul>
  </div>
</nav>

app/views/step2/sections/s1/_p1.html.erb
  <section class="slide kenBurns" data-name="p1" data-title="p1">
    <div class="content ">
      <div class="container">
        <div class="wrap top">

        <div class="fix-12-12">
          <div class="left">
            <h3 class="ae-1 font-weight-bold">First things first…</h3>
            <h1 class="huge ae-2 fromLeft bold">Why Focus on Syllabi?</h1>
          </div>
          <div class="fix-12-12 left margin-top-5">
            <ul class="grid grid-74 later equal">

            </ul>
            <ul class="grid margin-top-5">
              <li class="col-2-12 col-tablet-1-2 col-phablet-1-1 ae-1 fromCenter">
                <%= image_tag("https://cdn2.iconfinder.com/data/icons/circle-icons-1/64/zoomin-512.png")%>
              </li>
              <li class="col-9-12 col-tablet-1-2 col-phablet-1-1 fromCenter ae-4">
                <h3 class="large">Syllabi are a key feature of every academic course. It serves multiple purposes.</h3>
              </li>
            </ul>
          </div>

        </div>
      </div>
    </div>
  </section>

app/views/step2/sections/s1/_p2.html.erb
  <section class="slide kenBurns" data-name="p2" data-title="p2">
    <div class="content ">
      <div class="container">
        <div class="wrap top">

        <div class="fix-12-12">
          <div class="left">
            <h3 class="text-cueRED font-weight-bold">First things first…</h3>
            <h1 class="huge fromLeft s1-color bold">Why Focus on Syllabi?</h1>
          </div>
          <div class="fix-12-12 left margin-top-5">
            <ul class="grid grid-74 later equal">
              <li class="col-1-12 fromCenter">
                <a href="#" class="box-74">
                  <div class="thumbnail-74">
                    <%= image_tag("https://cdn2.iconfinder.com/data/icons/circle-icons-1/64/zoomin-512.png", class: "padding-1")%>
                  </div>
                </a>
              </li>
            </ul>
            <ul class="grid margin-top-5">
              <li class="col-2-12 ae-1 fromCenter">
                <%= image_tag("https://cdn2.iconfinder.com/data/icons/circle-icons-1/64/check-256.png")%>
              </li>
              <li class="col-9-12 col-tablet-1-2 col-phablet-1-1 fromCenter ae-4">
                <h3 class="large">Often, syllabi are seen as contracts between students and the instructor and as a record of what courses cover and how student outcomes and performance are evaluated for accountability purposes.</h3>
                <p> (Parkes & Harris, 2002).</p>
              </li>
            </ul>

          </div>

        </div>
      </div>
    </div>
  </section>

app/views/step2/sections/s1/_p3.html.erb
  <section class="slide kenBurns" data-name="p3" data-title="p3">
    <div class="content ">
      <div class="container">
        <div class="wrap top">

        <div class="fix-12-12">
          <div class="left">
            <h3 class="text-cueRED font-weight-bold">First things first…</h3>
            <h1 class="huge fromLeft s1-color bold">Why Focus on Syllabi?</h1>
          </div>
          <div class="fix-12-12 left margin-top-5">
            <ul class="grid grid-74 later equal">
              <li class="col-1-12 fromCenter">
                <a href="#" class="box-74">
                  <div class="thumbnail-74">
                    <%= image_tag("https://cdn2.iconfinder.com/data/icons/circle-icons-1/64/zoomin-512.png", class: "padding-1")%>
                  </div>
                </a>
              </li>
              <li class="col-1-12 fromCenter">
                <a href="#" class="box-74">
                  <div class="thumbnail-74">
                    <%= image_tag("https://cdn2.iconfinder.com/data/icons/circle-icons-1/64/check-256.png", class: "padding-1")%>
                  </div>
                </a>
              </li>
            </ul>
            <ul class="grid margin-top-5">
              <li class="col-2-12 ae-1 fromCenter">
                <%= image_tag("https://cdn2.iconfinder.com/data/icons/circle-icons-1/64/tools-512.png")%>
              </li>
              <li class="col-9-12 col-tablet-1-2 col-phablet-1-1 fromCenter ae-4">
                <h3 class="large">However, syllabi are also learning tools that can help students develop effective learning practices and strategies, as well as communication devices that share how teaching will be approached. </h3>
                <p>(Grunnert, 1997; Parkes & Harris, 2002)</p>
              </li>
            </ul>
          </div>

        </div>
      </div>
    </div>
  </section>

app/views/step2/sections/s1/_p4.html.erb
  <section class="slide kenBurns" data-name="p4" data-title="p4">
    <div class="content ">
      <div class="container">
        <div class="wrap top">

        <div class="fix-12-12">
          <div class="left">
            <h3 class="text-cueRED font-weight-bold">First things first…</h3>
            <h1 class="huge fromLeft s1-color bold">Why Focus on Syllabi?</h1>
          </div>
          <div class="fix-12-12 left margin-top-5">
            <ul class="grid grid-74">
              <li class="col-1-12 fromCenter">
                <a href="#" class="box-74">
                  <div class="thumbnail-74">
                    <%= image_tag("https://cdn2.iconfinder.com/data/icons/circle-icons-1/64/zoomin-512.png", class: "padding-1")%>
                  </div>
                </a>
              </li>
              <li class="col-1-12 fromCenter">
                <a href="#" class="box-74">
                  <div class="thumbnail-74">
                    <%= image_tag("https://cdn2.iconfinder.com/data/icons/circle-icons-1/64/check-256.png", class: "padding-1")%>
                  </div>
                </a>
              </li>
              <li class="col-1-12 fromCenter">
                <a href="#" class="box-74">
                  <div class="thumbnail-74">
                    <%= image_tag("https://cdn2.iconfinder.com/data/icons/circle-icons-1/64/tools-512.png", class: "padding-1")%>
                  </div>
                </a>
              </li>
            </ul>
            <ul class="grid margin-top-5">
              <li class="col-2-12 col-tablet-1-2 col-phablet-1-1 ae-1 fromCenter">
                <%= image_tag("https://cdn2.iconfinder.com/data/icons/circle-icons-1/64/compose-512.png", style: "width: 150px;")%>
              </li>
              <li class="col-9-12 col-tablet-1-2 col-phablet-1-1 fromCenter ae-4">
                <h2>While syllabi are not documents of what actually happens in the classroom, they serve varied purposes, making them rich sources of information about teaching as a practice.</h2>
              </li>
            </ul>
          </div>

        </div>
      </div>
    </div>
  </section>

app/views/step2/sections/s3/_p1.html.erb
<section class="slide whiteSlide" data-name="p1" data-title="p1">
  <div class="content ">
    <div class="container">
      <div class="wrap top">
        <div class="fix-12-12">
          <div class="left">
            <h3 class="ae-1 font-weight-bold">You might ask…</h3>
            <h1 class="big ae-2 fromLeft s3-color bold">What do Syllabi have to do with Racial Equity?</h1>
          </div>
          <div class="fix-12-12 left margin-top-5">
            <ul class="grid grid-74 later equal">

            </ul>
            <ul class="grid margin-top-5">
              <li class="col-2-12 col-tablet-1-2 col-phablet-1-1 ae-1 fromCenter">
                <%= image_tag("https://cdn2.iconfinder.com/data/icons/circle-icons-1/64/zoomin-512.png")%>
              </li>
              <li class="col-9-12 col-tablet-1-2 col-phablet-1-1 fromCenter ae-4">
                <h3 class="large">With few exceptions (historically black colleges and universities being the most notable), higher education institutions were founded and designed to serve white students, particularly those who are male, middle- to upper-class, heterosexual, able-bodied, and Christian.</h3>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>